tools:
    external_code_coverage:
        timeout: 720
filter:
    excluded_paths: [vendor/*, Tests/*]

checks:
    php:
        code_rating: true
        duplication: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        too_many_arguments: true
        single_namespace_per_use: true
        require_braces_around_control_structures: true
        remove_trailing_whitespace: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        psr2_class_declaration: true
        no_space_before_semicolon: true
        no_exit: true
        no_eval: true
        no_debug_code: true
        fix_identation_4spaces: true
        encourage_single_quotes: true
        deprecated_code_usage: true