language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer selfupdate
  - composer install --dev --prefer-source --no-interaction

script:
    - phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    email: false